# *- coding: utf-8 -*-
"""
namespace for ngofile using apipkg

generated by ngoproject.apipkg
"""

from __future__ import unicode_literals

import apipkg

apipkg.initpkg(
    'ngofile', {
        'NgoFileException': '.exceptions:NgoFileException',
        'CopyException': '.exceptions:CopyException',
        'NotExistingPathException': '.exceptions:NotExistingPathException',
        'NotADirectoryException': '.exceptions:NotADirectoryException',
        'NotAZipArchiveException': '.exceptions:NotAZipArchiveException',
        'advanced_copy': '._copy:advanced_copy',
        'list_files': '._list_files:list_files',
        'list_files_in_zip': '._list_files:list_files_in_zip',
        'PathList': '._pathlist:PathList',
        'LoadedModules': '._pathlist:LoadedModules',
        'list_all_dirs_in_modules': '._pathlist:list_all_dirs_in_modules',
    })
